name: run main.py

on:
  schedule:
    - cron: "*/2 * * * *" # roda a cada 2 minutos

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python main.py
